# Generated by Django 3.1 on 2020-08-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20200830_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='date_start',
        ),
    ]
