# Generated by Django 3.1 on 2020-08-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20200830_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='intro',
            field=models.TextField(max_length=2500),
        ),
    ]
